# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreqCMD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help', models.CharField(max_length=100)),
            ],
            managers=[
                ('with_count', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ToiNews',
            fields=[
                ('head_line', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=140)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
            managers=[
                ('with_count', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
            managers=[
                ('with_count', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-views'],
            },
            managers=[
                ('with_count', django.db.models.manager.Manager()),
            ],
        ),
    ]
