# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='help',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='toinews',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='weather',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='youtube',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='freqcmd',
            name='cmd',
        ),
    ]
